echofileserver: echofileserver.c
	gcc echofileserver.c -o echofileserver  -Wall -Wextra -pedantic -std=c17

echofileclient: echofileclient.c
	gcc echofileclient.c -o echofileclient -Wall -Wextra -pedantic -std=c17

all: echofileclient echofileserver
# run: echofileserver
	# ./echofileserver
	# rm echofileserver
